name = "Knight Quest"
author = "robonebi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9f137610f4b9b88e38db084eb8af7318e2481fa20c3c0d0137d42e66a7f0746"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.200"
