name = "Knight Quest"
author = "robonebi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93630705cd83fa7056b8e3085c4ca67a0d61ab58655268bc040d96cd6735c634"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.200"
