name = "Knight Quest"
author = "robonebi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d58b526c0c0fbe086ce2062b3a05d9588fc1955598dd3314acc5de7ad67b203f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.200"
