name = "Knight Quest"
author = "robonebi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24965a87836c8f33ac64d4c062ec622bb7757d460e1b6a0a14ee0414157ce942"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.200"
