name = "Knight Quest"
author = "robonebi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56ce49db8830784130306c72f94da6b3496f8de1784daabe78f9a0d21e857d8f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.200"
